before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
dockers:
  - image_templates:
      - ghcr.io/openchami/{{.ProjectName}}:latest
      - ghcr.io/openchami/{{.ProjectName}}:{{ .Tag }}
      - ghcr.io/openchami/{{.ProjectName}}:{{ .Major }}
      - ghcr.io/openchami/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - LICENSE
      - CHANGELOG.md
      - README.md
      - bin/magellan.sh
archives:
  - format: tar.gz
    rlcp: true
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - CHANGELOG.md
      - README.md
      - bin/magellan.sh
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append
