before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
dockers:
  - image_templates:
    - "bikeshack.azurecr.io/magellan:latest"
    - "bikeshack.azurecr.io/magellan:{{ .Major }}"
    - "bikeshack.azurecr.io/magellan:{{ .Major }}.{{ .Minor }}"
    - "bikeshack.azurecr.io/magellan:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    dockerfile: goreleaser.Dockerfile
    build_flag_templates:
    - "--pull"
    - "--no-cache"
    - "--build-arg=REGISTRY_HOST=docker.io/library/"
    # OCI annotations: https://github.com/opencontainers/image-spec/blob/main/annotations.md
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
archives:
  - format: tar.gz
    rlcp: true
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - migrations/*
      - LICENSE
      - CHANGELOG.md
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append
