scan:
  hosts:
    - "172.16.1.15"
  subnets:
    - "172.16.0.0"
    - "172.16.0.0/24"
  subnet-masks:
  ports:
    - 433
  disable-probing: false
collect:
  # host: smd-host
  # port: smd-port
  username: "admin"
  password: "password"
  protocol: "https"
  output: "/tmp/magellan/data/"
  threads: 1
  force-update: false
  cacert: "cacert.pem"
update:
  host:
  port: 443
  username: "admin"
  password: "password"
  transfer-protocol: "HTTP"
  protocol: "https"
  firmware:
    url:
    version:
  component:
  secure-tls: false
  status: false
concurrency: 1
timeout: 30
verbose: true
db:
  path: "/tmp/magellan/magellan.db"
