# Config files like this can be provided to Magellan in two ways:
# - Explicitly, via the `-c` flag
# - Implicitly, by placing the file in $XDG_CONFIG_HOME/magellan/config.yaml
#   - If $XDG_CONFIG_HOME is not defined, it is assumed to be ~/.config
# Also, while this example uses YAML, other formats are also supported via the Go Viper package.
# File type will be auto-detected based on extension, e.g. ~/.config/magellan/config.json will be parsed as JSON.
scan:
  hosts:
    - "172.16.1.15"
    - "10.0.0.1"
  subnets:
    - "172.16.0.0"
    - "172.16.0.0/24"
  subnet-masks:
    - "255.255.255.0"
  ports:
    - 443
  disable-probing: false
  disable-caching: false
  protocol: "tcp"
  scheme: "https"
collect:
  protocol: "tcp"
  output: "/tmp/magellan/data/"
  threads: 1
  force-update: false
  cacert: "cacert.pem"
update:
  host:
  port: 443
  transfer-protocol: "https"
  firmware:
    url:
    version:
  component:
  secure-tls: false
  status: false
power:
  cacert: "cacert.pem"
concurrency: 1
timeout: 30
verbose: true
cache:
  path: "/tmp/magellan/magellan.db"
