package power

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/OpenCHAMI/magellan/internal/format"
	"github.com/OpenCHAMI/magellan/pkg/bmc"
	"github.com/OpenCHAMI/magellan/pkg/crawler"
	"gopkg.in/yaml.v3"

	"github.com/rs/zerolog/log"
	"github.com/stmcginnis/gofish"
	"github.com/stmcginnis/gofish/redfish"
)

type CrawlableNode struct {
	ClusterID  string
	ConnConfig crawler.CrawlerConfig
	NodeID     string
}
type PowerInfo struct {
	ClusterID string
	State     redfish.PowerState
}

// ParseInventory reads parameters relevant to power control from the kind of YAML file generated by the `collect` command.
//
// Parameters:
//   - filename: the path of the YAML file to parse for inventory data, or `-` for stdin.
//
// Returns:
//   - []bmc.Node: A slice of structs containing relevant details for connecting to a node via its BMC.
//   - error: An error object if any error occurs during the connection or reset process.
func ParseInventory(filename string, dataFormat format.DataFormat) ([]bmc.Node, error) {
	// Read `collect`ed data from YAML file
	var (
		contents []byte
		err      error
	)
	if filename == "-" {
		filename = "[stdin]"
		contents, err = io.ReadAll(os.Stdin)
	} else {
		contents, err = os.ReadFile(filename)
	}
	if err != nil {
		log.Error().Err(err).Msgf("failed to read collected inventory from %s", filename)
		return nil, err
	}

	var inventory []struct {
		ID      string                    `json:"ID" yaml:"ID"`
		FQDN    string                    `json:"FQDN" yaml:"FQDN"`
		Systems []crawler.InventoryDetail `json:"Systems" yaml:"Systems"`
	}
	switch dataFormat {
	case format.FORMAT_JSON:
		err = json.Unmarshal(contents, &inventory)
	case format.FORMAT_YAML:
		err = yaml.Unmarshal(contents, &inventory)
	default:
		err = fmt.Errorf("unknown input format: %v", dataFormat)
	}
	if err != nil {
		log.Error().Err(err).Msgf("failed to unmarshal contents of collected inventory file %s", filename)
		return nil, err
	}

	nodelist := make([]bmc.Node, 0, len(inventory))
	for i := range inventory {
		systems := inventory[i].Systems
		for j := range systems {
			nodelist = append(nodelist, bmc.Node{
				// TODO: This assumes indices in the Systems list correspond to nodes' "…nX" xname components.
				// If the list is reordered at any point, or if nodes were missing during crawl, this may not hold!
				// FIXME: This assumes strict xname formatting! To become xname-agnostic, this should be
				// replaced with some other cluster-wide ID (which the BMC/ComputerSystem itself won't know, so
				// it'll have to be generated/looked up from somewhere else).
				ClusterID: fmt.Sprintf("%sn%d", inventory[i].ID, j),
				BmcIP:     inventory[i].FQDN,
				NodeID:    systems[j].NodeID,
			})
		}
	}

	return nodelist, nil
}

// ResetComputerSystem connects to a BMC (Baseboard Management Controller) using the provided configuration,
// retrieves the ServiceRoot, and retrieves the list of supported reset types for the target ComputerSystem.
//
// Parameters:
//   - node: A CrawlableNode struct containing the node's xname, index within the BMC, and a CrawlerConfig to connect to the BMC.
//
// Returns:
//   - []redfish.ResetType: a slice of Redfish reset types supported on the node.
//   - error: An error object if any error occurs during the connection or reset process.
func GetResetTypes(node CrawlableNode) ([]redfish.ResetType, error) {
	log.Debug().Msgf("polling %s for reset types", node.ConnConfig.URI)

	// Obtain an active (cached) vendor-aware client
	client, err := bmc.DefaultManager.CachedClient(node.ConnConfig)
	if err != nil {
		return nil, err
	}
	return client.GetResetTypes(node.NodeID)
}

// PollBMCPowerStates connects to a BMC (Baseboard Management Controller) using the provided configuration,
// retrieves the ServiceRoot, and retrieves the current power state for each ComputerSystem in each Chassis.
//
// Parameters:
//   - node: A CrawlableNode struct containing the target node's xname, index within the BMC, and a crawler.CrawlerConfig struct.
//
// Returns:
//   - redfish.PowerState: The current power state of the node. (Custom string subtype)
//   - error: An error object if any error occurs during the connection or retrieval process.
func GetPowerState(node CrawlableNode) (redfish.PowerState, error) {
	log.Debug().Msgf("polling %s for power states", node.ConnConfig.URI)

	// Obtain an active (cached) vendor-aware client
	client, err := bmc.DefaultManager.CachedClient(node.ConnConfig)
	if err != nil {
		return "", err
	}
	return client.GetPowerState(node.NodeID)
}

// ResetComputerSystem connects to a BMC (Baseboard Management Controller) using the provided configuration,
// retrieves the ServiceRoot, and issues a reset of the specified type to a particular computer system.
//
// Parameters:
//   - node: A CrawlableNode struct containing the node's xname, index within the BMC, and a CrawlerConfig to connect to the BMC.
//   - resetType: A redfish.ResetType parameter, specifying the manner in which the target ComputerSystem should be reset.
//
// Returns:
//   - error: An error object if any error occurs during the connection or reset process.
func ResetComputerSystem(node CrawlableNode, resetType redfish.ResetType) error {
	log.Debug().Msgf("resetting computer system %s: %s", node.ClusterID, resetType)

	// Use a fresh (uncached) vendor-aware client and log out when done.
	client, err := bmc.DefaultManager.Client(node.ConnConfig)
	if err != nil {
		return err
	}
	defer client.Logout()

	return client.Reset(node.NodeID, resetType)
}

// GetBMCSession returns an already-active gofish BMC client, creating a new one if necessary.
// This facilitates keeping the clients open for efficiency.
//
// Parameters:
//   - config: A CrawlerConfig struct containing the URI, username, password, and other connection details.
//
// Returns: none.
func GetBMCSession(config crawler.CrawlerConfig) (*gofish.APIClient, error) {
	client, err := bmc.DefaultManager.CachedClient(config)
	if err != nil {
		return nil, err
	}
	return client.Gofish(), nil
}

// LogoutBMCSessions logs out all active gofish BMC clients, which we normally like to keep open for efficiency.
// Logging out should be done as a post-execution cleanup step.
//
// Parameters: none.
//
// Returns: none.
func LogoutBMCSessions() {
	bmc.DefaultManager.LogoutAll()
}
