package bmc

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/openchami/magellan/internal/format"
	"github.com/openchami/magellan/pkg/models"
	"github.com/openchami/magellan/pkg/secrets"
	"github.com/rs/zerolog/log"
	"github.com/stretchr/testify/assert/yaml"
)

type BMCCredentials struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
type Node struct {
	ClusterID string `yaml:"cluster_id"`
	BmcIP     string `yaml:"bmc_ip"`
	NodeID    string `yaml:"node_id"`
}

func GetBMCCredentialsDefault(store secrets.SecretStore) (BMCCredentials, error) {
	var creds BMCCredentials
	if store == nil {
		return creds, fmt.Errorf("invalid secrets store")
	}
	if strCreds, err := store.GetSecretByID(secrets.DEFAULT_KEY); err != nil {
		return creds, fmt.Errorf("get default BMC credentials from secret store: %w", err)
	} else {
		// Default URI credentials found, use them.
		if err = json.Unmarshal([]byte(strCreds), &creds); err != nil {
			return creds, fmt.Errorf("get default BMC credentials from secret store: failed to unmarshal: %w", err)
		}
		return creds, nil
	}
}

func GetBMCCredentials(store secrets.SecretStore, id string) (BMCCredentials, error) {
	var creds BMCCredentials
	if store == nil {
		return creds, fmt.Errorf("invalid secrets store")
	}
	if strCreds, err := store.GetSecretByID(id); err != nil {
		return creds, fmt.Errorf("get BMC credentials from secret store: %w", err)
	} else {
		// Specific URI credentials found, use them.
		if err = json.Unmarshal([]byte(strCreds), &creds); err != nil {
			return creds, fmt.Errorf("get BMC credentials from secret store: failed to unmarshal: %w", err)
		}
	}

	return creds, nil
}

func GetBMCCredentialsOrDefault(store secrets.SecretStore, id string) BMCCredentials {
	var (
		creds BMCCredentials
		err   error
	)

	if id == "" {
		return creds
	}

	if id == secrets.DEFAULT_KEY {
		creds, _ = GetBMCCredentialsDefault(store)
		return creds
	}

	if creds, err = GetBMCCredentials(store, id); err != nil {
		if defaultSecret, err := GetBMCCredentialsDefault(store); err == nil {
			// Default credentials found, use them.
			creds = defaultSecret
		}
	}

	return creds
}

// ParseInventory reads parameters relevant to power control from the kind of YAML file generated by the `collect` command.
//
// Parameters:
//   - filename: the path of the YAML file to parse for inventory data, or `-` for stdin.
//
// Returns:
//   - []bmc.Node: A slice of structs containing relevant details for connecting to a node via its BMC.
//   - error: An error object if any error occurs during the connection or reset process.
func ParseInventory(filename string, dataFormat format.DataFormat) ([]Node, error) {
	// Read `collect`ed data from YAML file
	var (
		contents []byte
		err      error
	)
	if filename == "-" {
		filename = "[stdin]"
		contents, err = io.ReadAll(os.Stdin)
	} else {
		contents, err = os.ReadFile(filename)
	}
	if err != nil {
		log.Error().Err(err).Msgf("failed to read collected inventory from %s", filename)
		return nil, err
	}

	var inventory []struct {
		ID      string                   `json:"ID" yaml:"ID"`
		FQDN    string                   `json:"FQDN" yaml:"FQDN"`
		Systems []models.InventoryDetail `json:"Systems" yaml:"Systems"`
	}
	switch dataFormat {
	case format.FORMAT_JSON:
		err = json.Unmarshal(contents, &inventory)
	case format.FORMAT_YAML:
		err = yaml.Unmarshal(contents, &inventory)
	default:
		err = fmt.Errorf("unknown input format: %v", dataFormat)
	}
	if err != nil {
		log.Error().Err(err).Msgf("failed to unmarshal contents of collected inventory file %s", filename)
		return nil, err
	}

	nodelist := make([]Node, 0, len(inventory))
	for i := range inventory {
		systems := inventory[i].Systems
		for j := range systems {
			nodelist = append(nodelist, Node{
				// TODO: This assumes indices in the Systems list correspond to nodes' "…nX" xname components.
				// If the list is reordered at any point, or if nodes were missing during crawl, this may not hold!
				// FIXME: This assumes strict xname formatting! To become xname-agnostic, this should be
				// replaced with some other cluster-wide ID (which the BMC/ComputerSystem itself won't know, so
				// it'll have to be generated/looked up from somewhere else).
				ClusterID: fmt.Sprintf("%sn%d", inventory[i].ID, j),
				BmcIP:     inventory[i].FQDN,
				NodeID:    systems[j].NodeID,
			})
		}
	}

	return nodelist, nil
}
